name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug"]
body:
- type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
- type: input
    id: component
    attributes:
      label: Which Component
      description: 
      placeholder: Tell us which component has bug
    validations:
      required: true
- type: input
    id: semi-version
    attributes:
      label: Semi Version
      description: 
      placeholder: Which version you using 
    validations:
      required: true
- type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "something wrong"
    validations:
      required: true
- type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What did you expect to happen?
      value: "should work fine"
    validations:
      required: true
- type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
