name: "Get Commit Hash on PR Merge"

on:
  pull_request:
    branches: [main, release]
    types:
      - closed

jobs:
  get_commit_hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hashes
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          echo "Current Commit: ${{ github.sha }}"
          echo "Before Commit: ${{ github.event.pull_request.before }}"
