name: performance

on:
  workflow_dispatch:

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/performance/main
          chmod +x ./main
          ./main --mode=all
        env:
          TOS_PASSWD: ${{ secrets.TOS_PASSWD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
